import React from "react";
import type { Metadata } from "next";
import Link from "next/link";

async function getData() {
  const respons = await fetch("https://jsonplaceholder.typicode.com/posts", {
    next: {
      revalidate: 60,
    },
  });

  if (!respons.ok) throw new Error("unable to fetch post");
  return respons.json();
}

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by Blog",
};
const Blog = async () => {
  const posts = await getData();
  return (
    <>
      <h1 className="text-8xl text-center">Blog</h1>
      <ul>
        {posts.map((post: any) => (
          <li key={post.id}>
            <Link href={`/blog/${post.id}`}>{post.title}</Link>
          </li>
        ))}
      </ul>
    </>
  );
};

export default Blog;
