import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "About",
  description: "Generated by About",
};

const About = () => {
  return <h3 className="text-lg text-center">Select subtitle</h3>;
};

export default About;
